queries:
- include: "*"
- exclude: "cpp/class-many-fields"
- exclude: "cpp/long-switch"
- exclude: "cpp/trivial-switch"

  cpp:
    index:
      build_command:
      - "g++ -o MyCinema MyCinema.cpp"
      - "./MyCinema"
